trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    java -version
    mvn -version
  displayName: 'Display Java and Maven versions'

- script: |
    mvn -B package
  displayName: 'Build with Maven'

- script: |
    mvn test
  displayName: 'Run Maven tests'