trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'src/Selenium/pom.xml' # Het pad naar pom.xml als deze zich in de root bevindt
    goals: 'test' # Hiermee worden alleen de tests uitgevoerd
    options: '-B' # Batch mode maakt de build output minder rommelig
    publishJUnitResults: true # Dit zal de JUnit testresultaten publiceren
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Het pad naar de testresultaten

- task: PublishTestResults@2
  condition: succeededOrFailed() # Altijd publiceren, zelfs als de build mislukt
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Het pad naar de testresultaten